[project]
name = "cvzone-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mediapipe<=0.10.14",
    "numpy",
    "opencv-python>=4",
]
